import Head from 'next/head';
import styles from '../styles/Home.module.css';
import App from '../components/App';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creative Process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App></App>
      {/* <Creative /> */}
    </div>
  );
}
