import Head from 'next/head';
import Image from 'next/image';
import Creative from '../components/Creative';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creative Process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Creative />
    </div>
  );
}
